-- Secure manual Wave payment verification workflow.
revoke execute on function public.confirm_payment() from public,anon,authenticated;
create table if not exists public.payment_claims(id uuid primary key default gen_random_uuid(),user_id uuid not null references auth.users(id) on delete cascade,provider text not null default 'wave' check(provider in('wave','manual')),plan_name text not null,amount integer not null check(amount>=0 and amount<=10000000),status text not null default 'submitted' check(status in('submitted','approved','rejected')),submitted_at timestamptz not null default now(),reviewed_at timestamptz,reviewed_by uuid references auth.users(id) on delete set null,admin_note text);
create unique index if not exists uq_payment_claim_open_user on public.payment_claims(user_id) where status='submitted';
create index if not exists idx_payment_claims_status_date on public.payment_claims(status,submitted_at desc);
alter table public.payment_claims enable row level security;
drop policy if exists payment_claims_read_own_admin on public.payment_claims;
create policy payment_claims_read_own_admin on public.payment_claims for select to authenticated using(user_id=(select auth.uid()) or public.is_admin());
revoke insert,update,delete on public.payment_claims from anon,authenticated;
grant select on public.payment_claims to authenticated;
create or replace function public.student_submit_payment_claim() returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid; v_plan text; v_amount integer; v_enabled boolean; begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; if not exists(select 1 from public.profiles p where p.id=auth.uid() and p.status='pending') then raise exception 'Only pending student accounts can submit payment' using errcode='42501'; end if; select plan_name,registration_price,payments_enabled into v_plan,v_amount,v_enabled from public.school_settings where id='global'; if not coalesce(v_enabled,false) then raise exception 'Online payment is disabled' using errcode='42501'; end if; select id into v_id from public.payment_claims where user_id=auth.uid() and status='submitted' limit 1; if found then return v_id; end if; insert into public.payment_claims(user_id,provider,plan_name,amount,status) values(auth.uid(),'wave',v_plan,v_amount,'submitted') returning id into v_id; return v_id; end; $$;
create or replace function public.admin_review_payment_claim(p_claim_id uuid,p_decision text,p_note text default null) returns boolean language plpgsql security definer set search_path='' as $$ declare v_user uuid; begin if not public.is_admin() then raise exception 'Admin required' using errcode='42501'; end if; if p_decision not in('approved','rejected') then raise exception 'Invalid decision' using errcode='22023'; end if; select user_id into v_user from public.payment_claims where id=p_claim_id and status='submitted' for update; if not found then return false; end if; update public.payment_claims set status=p_decision,reviewed_at=now(),reviewed_by=auth.uid(),admin_note=nullif(btrim(p_note),'') where id=p_claim_id; if p_decision='approved' then update public.profiles set status='active' where id=v_user and status='pending'; end if; return true; end; $$;
revoke execute on function public.student_submit_payment_claim() from public,anon;
revoke execute on function public.admin_review_payment_claim(uuid,text,text) from public,anon;
grant execute on function public.student_submit_payment_claim() to authenticated;
grant execute on function public.admin_review_payment_claim(uuid,text,text) to authenticated;
