-- V3.3.1 product platform: white-label school identity + secure instructor workspace.
create table if not exists public.school_settings (
  id text primary key default 'global' check (id = 'global'), app_name text not null default 'eAutoecole', school_name text not null default 'Auto-école',
  tagline text not null default 'Apprendre. S’entraîner. Réussir.', hero_title text not null default 'Votre permis commence ici.',
  hero_message text not null default 'Un parcours guidé, des entraînements adaptés et un suivi humain pour progresser avec confiance.',
  phone text, phone_href text, whatsapp text, email text, address text, city text not null default 'Dakar', logo_url text,
  primary_color text not null default '#155EEF', accent_color text not null default '#12B76A',
  updated_at timestamptz not null default now(), updated_by uuid references auth.users(id) on delete set null
);
insert into public.school_settings(id,app_name,school_name,tagline,hero_title,hero_message,phone,phone_href,whatsapp,email,address,city)
values('global','eAutoecole','Auto-école','Apprendre. S’entraîner. Réussir.','Votre permis commence ici.','Un parcours guidé, des entraînements adaptés et un suivi humain pour progresser avec confiance.','77 583 20 37','+221775832037','221775832037','eautoecole1@gmail.com','Dakar HLM5, Castors Parc Nadio, Keurmassar','Dakar') on conflict(id) do nothing;
alter table public.school_settings enable row level security;
drop policy if exists school_settings_read_all on public.school_settings;
create policy school_settings_read_all on public.school_settings for select to anon,authenticated using(true);
drop policy if exists school_settings_admin_update on public.school_settings;
create policy school_settings_admin_update on public.school_settings for update to authenticated using(public.is_admin()) with check(public.is_admin());
alter table public.profiles add column if not exists account_role text not null default 'student';
do $$ begin if not exists(select 1 from pg_constraint where conname='profiles_account_role_check' and conrelid='public.profiles'::regclass) then alter table public.profiles add constraint profiles_account_role_check check(account_role in ('student','instructor')); end if; end $$;
create or replace function public.is_instructor() returns boolean language sql stable security definer set search_path='' as $$ select coalesce(auth.jwt()->'app_metadata'->>'role','') in ('instructor','admin'); $$;
create table if not exists public.instructor_assignments(id uuid primary key default gen_random_uuid(),instructor_id uuid not null references auth.users(id) on delete cascade,student_id uuid not null references auth.users(id) on delete cascade,status text not null default 'active' check(status in ('active','ended')),created_at timestamptz not null default now(),ended_at timestamptz,created_by uuid references auth.users(id) on delete set null,check(instructor_id<>student_id));
create unique index if not exists uq_instructor_assignment_active_student on public.instructor_assignments(student_id) where status='active';
create index if not exists idx_instructor_assignments_instructor on public.instructor_assignments(instructor_id,status,created_at desc);
create table if not exists public.instructor_notes(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.instructor_assignments(id) on delete cascade,author_id uuid not null references auth.users(id) on delete cascade,note text not null check(char_length(btrim(note)) between 1 and 3000),visible_to_student boolean not null default true,created_at timestamptz not null default now());
create index if not exists idx_instructor_notes_assignment on public.instructor_notes(assignment_id,created_at desc);
create table if not exists public.instructor_goals(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.instructor_assignments(id) on delete cascade,title text not null check(char_length(btrim(title)) between 1 and 220),details text,status text not null default 'active' check(status in ('active','done','cancelled')),due_date date,created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_instructor_goals_assignment on public.instructor_goals(assignment_id,status,created_at desc);
create table if not exists public.driving_sessions(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.instructor_assignments(id) on delete cascade,scheduled_at timestamptz not null,duration_minutes integer not null default 60 check(duration_minutes between 15 and 240),location text,focus text,status text not null default 'planned' check(status in ('planned','completed','cancelled')),instructor_comment text,created_by uuid not null references auth.users(id) on delete cascade,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create index if not exists idx_driving_sessions_assignment on public.driving_sessions(assignment_id,scheduled_at desc);
alter table public.instructor_assignments enable row level security; alter table public.instructor_notes enable row level security; alter table public.instructor_goals enable row level security; alter table public.driving_sessions enable row level security;
drop policy if exists instructor_assignments_read on public.instructor_assignments;
create policy instructor_assignments_read on public.instructor_assignments for select to authenticated using(public.is_admin() or instructor_id=(select auth.uid()) or student_id=(select auth.uid()));
drop policy if exists instructor_notes_read on public.instructor_notes;
create policy instructor_notes_read on public.instructor_notes for select to authenticated using(public.is_admin() or exists(select 1 from public.instructor_assignments a where a.id=instructor_notes.assignment_id and (a.instructor_id=(select auth.uid()) or (a.student_id=(select auth.uid()) and instructor_notes.visible_to_student))));
drop policy if exists instructor_goals_read on public.instructor_goals;
create policy instructor_goals_read on public.instructor_goals for select to authenticated using(public.is_admin() or exists(select 1 from public.instructor_assignments a where a.id=instructor_goals.assignment_id and (a.instructor_id=(select auth.uid()) or a.student_id=(select auth.uid()))));
drop policy if exists driving_sessions_read on public.driving_sessions;
create policy driving_sessions_read on public.driving_sessions for select to authenticated using(public.is_admin() or exists(select 1 from public.instructor_assignments a where a.id=driving_sessions.assignment_id and (a.instructor_id=(select auth.uid()) or a.student_id=(select auth.uid()))));
revoke insert,update,delete on public.instructor_assignments,public.instructor_notes,public.instructor_goals,public.driving_sessions from anon,authenticated;
grant select on public.instructor_assignments,public.instructor_notes,public.instructor_goals,public.driving_sessions to authenticated;
create or replace function public.save_school_settings(p_settings jsonb) returns public.school_settings language plpgsql security definer set search_path='' as $$ declare v_row public.school_settings; begin if not public.is_admin() then raise exception 'Admin required' using errcode='42501'; end if; update public.school_settings set app_name=coalesce(nullif(btrim(p_settings->>'app_name'),''),app_name),school_name=coalesce(nullif(btrim(p_settings->>'school_name'),''),school_name),tagline=coalesce(nullif(btrim(p_settings->>'tagline'),''),tagline),hero_title=coalesce(nullif(btrim(p_settings->>'hero_title'),''),hero_title),hero_message=coalesce(nullif(btrim(p_settings->>'hero_message'),''),hero_message),phone=nullif(btrim(p_settings->>'phone'),''),phone_href=nullif(btrim(p_settings->>'phone_href'),''),whatsapp=nullif(regexp_replace(coalesce(p_settings->>'whatsapp',''),'[^0-9]','','g'),''),email=nullif(btrim(p_settings->>'email'),''),address=nullif(btrim(p_settings->>'address'),''),city=coalesce(nullif(btrim(p_settings->>'city'),''),city),logo_url=nullif(btrim(p_settings->>'logo_url'),''),primary_color=case when coalesce(p_settings->>'primary_color','')~'^#[0-9A-Fa-f]{6}$' then p_settings->>'primary_color' else primary_color end,accent_color=case when coalesce(p_settings->>'accent_color','')~'^#[0-9A-Fa-f]{6}$' then p_settings->>'accent_color' else accent_color end,updated_at=now(),updated_by=auth.uid() where id='global' returning * into v_row; return v_row; end; $$;
create or replace function public.admin_set_account_role(target_user_id uuid,new_role text) returns boolean language plpgsql security definer set search_path='' as $$ declare v_current_role text; begin if not public.is_admin() then raise exception 'Admin required' using errcode='42501'; end if; if new_role not in ('student','instructor') then raise exception 'Invalid role' using errcode='22023'; end if; if target_user_id is null or target_user_id=auth.uid() then raise exception 'Cannot change this account' using errcode='42501'; end if; select coalesce(raw_app_meta_data->>'role','') into v_current_role from auth.users where id=target_user_id for update; if not found then return false; end if; if v_current_role='admin' then raise exception 'Admin role cannot be changed here' using errcode='42501'; end if; update auth.users set raw_app_meta_data=coalesce(raw_app_meta_data,'{}'::jsonb)||jsonb_build_object('role',new_role),updated_at=now() where id=target_user_id; update public.profiles set account_role=new_role where id=target_user_id; if new_role='student' then update public.instructor_assignments set status='ended',ended_at=now() where instructor_id=target_user_id and status='active'; end if; return true; end; $$;
create or replace function public.admin_assign_instructor(p_instructor_id uuid,p_student_id uuid) returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid; v_role text; begin if not public.is_admin() then raise exception 'Admin required' using errcode='42501'; end if; if p_instructor_id is null or p_student_id is null or p_instructor_id=p_student_id then raise exception 'Invalid assignment' using errcode='22023'; end if; select account_role into v_role from public.profiles where id=p_instructor_id; if coalesce(v_role,'')<>'instructor' then raise exception 'Selected user is not an instructor' using errcode='22023'; end if; if not exists(select 1 from public.profiles where id=p_student_id and account_role='student' and status='active') then raise exception 'Student must be active' using errcode='22023'; end if; update public.instructor_assignments set status='ended',ended_at=now() where student_id=p_student_id and status='active'; insert into public.instructor_assignments(instructor_id,student_id,status,created_by) values(p_instructor_id,p_student_id,'active',auth.uid()) returning id into v_id; return v_id; end; $$;
create or replace function public.admin_end_instructor_assignment(p_assignment_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ begin if not public.is_admin() then raise exception 'Admin required' using errcode='42501'; end if; update public.instructor_assignments set status='ended',ended_at=now() where id=p_assignment_id and status='active'; return found; end; $$;
create or replace function public.get_instructor_students() returns jsonb language sql stable security definer set search_path='' as $$ with assigned as (select a.id assignment_id,a.student_id,p.prenom,p.telephone,p.photo_url,p.status from public.instructor_assignments a join public.profiles p on p.id=a.student_id where a.status='active' and (public.is_admin() or a.instructor_id=auth.uid())), attempts as (select l.user_id,count(*) filter(where l.is_correct is not null)::int answered,count(*) filter(where l.is_correct is true)::int correct from public.learning_attempts l where l.user_id in(select student_id from assigned) group by l.user_id), points as (select user_id,coalesce(sum(points),0)::int points from public.learning_points_ledger where user_id in(select student_id from assigned) group by user_id), topic_stats as (select l.user_id,l.topic,count(*)::int attempts,round(100.0*count(*) filter(where l.is_correct is true)/nullif(count(*) filter(where l.is_correct is not null),0))::int accuracy from public.learning_attempts l where l.user_id in(select student_id from assigned) and l.topic is not null and l.is_correct is not null group by l.user_id,l.topic) select coalesce(jsonb_agg(jsonb_build_object('assignmentId',a.assignment_id,'studentId',a.student_id,'prenom',a.prenom,'telephone',a.telephone,'photoUrl',a.photo_url,'status',a.status,'points',coalesce(p.points,0),'answered',coalesce(t.answered,0),'correct',coalesce(t.correct,0),'accuracy',case when coalesce(t.answered,0)>0 then round(100.0*t.correct/t.answered)::int else 0 end,'weakTopics',coalesce((select jsonb_agg(jsonb_build_object('topic',x.topic,'accuracy',coalesce(x.accuracy,0),'attempts',x.attempts) order by coalesce(x.accuracy,0),x.attempts desc) from(select * from topic_stats ts where ts.user_id=a.student_id and ts.attempts>=2 order by coalesce(ts.accuracy,0),ts.attempts desc limit 5)x),'[]'::jsonb)) order by a.prenom),'[]'::jsonb) from assigned a left join attempts t on t.user_id=a.student_id left join points p on p.user_id=a.student_id; $$;
create or replace function public.get_student_instructor_summary() returns jsonb language sql stable security definer set search_path='' as $$ with a as(select ia.id,ia.instructor_id,ia.student_id from public.instructor_assignments ia where ia.student_id=auth.uid() and ia.status='active' limit 1) select case when not exists(select 1 from a) then null else jsonb_build_object('assignmentId',(select id from a),'instructor',(select jsonb_build_object('id',p.id,'prenom',p.prenom,'telephone',p.telephone,'photoUrl',p.photo_url) from a join public.profiles p on p.id=a.instructor_id),'goals',coalesce((select jsonb_agg(jsonb_build_object('id',g.id,'title',g.title,'details',g.details,'status',g.status,'dueDate',g.due_date) order by g.status,g.created_at desc) from public.instructor_goals g where g.assignment_id=(select id from a) and g.status<>'cancelled'),'[]'::jsonb),'sessions',coalesce((select jsonb_agg(jsonb_build_object('id',s.id,'scheduledAt',s.scheduled_at,'durationMinutes',s.duration_minutes,'location',s.location,'focus',s.focus,'status',s.status,'comment',s.instructor_comment) order by s.scheduled_at desc) from public.driving_sessions s where s.assignment_id=(select id from a) and s.scheduled_at>now()-interval '30 days' limit 8),'[]'::jsonb),'notes',coalesce((select jsonb_agg(jsonb_build_object('id',n.id,'note',n.note,'createdAt',n.created_at) order by n.created_at desc) from public.instructor_notes n where n.assignment_id=(select id from a) and n.visible_to_student limit 8),'[]'::jsonb)) end; $$;
create or replace function public.instructor_add_note(p_assignment_id uuid,p_note text,p_visible_to_student boolean default true) returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid; begin if not public.is_instructor() then raise exception 'Instructor required' using errcode='42501'; end if; if nullif(btrim(p_note),'') is null then raise exception 'Note required' using errcode='22023'; end if; if not exists(select 1 from public.instructor_assignments a where a.id=p_assignment_id and a.status='active' and (public.is_admin() or a.instructor_id=auth.uid())) then raise exception 'Assignment denied' using errcode='42501'; end if; insert into public.instructor_notes(assignment_id,author_id,note,visible_to_student) values(p_assignment_id,auth.uid(),btrim(p_note),coalesce(p_visible_to_student,true)) returning id into v_id; return v_id; end; $$;
create or replace function public.instructor_create_goal(p_assignment_id uuid,p_title text,p_details text default null,p_due_date date default null) returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid; begin if not public.is_instructor() then raise exception 'Instructor required' using errcode='42501'; end if; if nullif(btrim(p_title),'') is null then raise exception 'Goal title required' using errcode='22023'; end if; if not exists(select 1 from public.instructor_assignments a where a.id=p_assignment_id and a.status='active' and (public.is_admin() or a.instructor_id=auth.uid())) then raise exception 'Assignment denied' using errcode='42501'; end if; insert into public.instructor_goals(assignment_id,title,details,due_date,created_by) values(p_assignment_id,btrim(p_title),nullif(btrim(p_details),''),p_due_date,auth.uid()) returning id into v_id; return v_id; end; $$;
create or replace function public.instructor_update_goal_status(p_goal_id uuid,p_status text) returns boolean language plpgsql security definer set search_path='' as $$ begin if not public.is_instructor() then raise exception 'Instructor required' using errcode='42501'; end if; if p_status not in('active','done','cancelled') then raise exception 'Invalid goal status' using errcode='22023'; end if; update public.instructor_goals g set status=p_status,updated_at=now() where g.id=p_goal_id and exists(select 1 from public.instructor_assignments a where a.id=g.assignment_id and (public.is_admin() or a.instructor_id=auth.uid())); return found; end; $$;
create or replace function public.instructor_schedule_session(p_assignment_id uuid,p_scheduled_at timestamptz,p_duration_minutes integer default 60,p_location text default null,p_focus text default null) returns uuid language plpgsql security definer set search_path='' as $$ declare v_id uuid; begin if not public.is_instructor() then raise exception 'Instructor required' using errcode='42501'; end if; if p_scheduled_at is null or p_duration_minutes not between 15 and 240 then raise exception 'Invalid session' using errcode='22023'; end if; if not exists(select 1 from public.instructor_assignments a where a.id=p_assignment_id and a.status='active' and (public.is_admin() or a.instructor_id=auth.uid())) then raise exception 'Assignment denied' using errcode='42501'; end if; insert into public.driving_sessions(assignment_id,scheduled_at,duration_minutes,location,focus,created_by) values(p_assignment_id,p_scheduled_at,p_duration_minutes,nullif(btrim(p_location),''),nullif(btrim(p_focus),''),auth.uid()) returning id into v_id; return v_id; end; $$;
create or replace function public.instructor_update_session(p_session_id uuid,p_status text,p_comment text default null) returns boolean language plpgsql security definer set search_path='' as $$ begin if not public.is_instructor() then raise exception 'Instructor required' using errcode='42501'; end if; if p_status not in('planned','completed','cancelled') then raise exception 'Invalid session status' using errcode='22023'; end if; update public.driving_sessions s set status=p_status,instructor_comment=nullif(btrim(p_comment),''),updated_at=now() where s.id=p_session_id and exists(select 1 from public.instructor_assignments a where a.id=s.assignment_id and (public.is_admin() or a.instructor_id=auth.uid())); return found; end; $$;
revoke execute on function public.is_instructor(),public.save_school_settings(jsonb),public.admin_set_account_role(uuid,text),public.admin_assign_instructor(uuid,uuid),public.admin_end_instructor_assignment(uuid),public.get_instructor_students(),public.get_student_instructor_summary(),public.instructor_add_note(uuid,text,boolean),public.instructor_create_goal(uuid,text,text,date),public.instructor_update_goal_status(uuid,text),public.instructor_schedule_session(uuid,timestamptz,integer,text,text),public.instructor_update_session(uuid,text,text) from public,anon;
grant execute on function public.is_instructor(),public.save_school_settings(jsonb),public.admin_set_account_role(uuid,text),public.admin_assign_instructor(uuid,uuid),public.admin_end_instructor_assignment(uuid),public.get_instructor_students(),public.get_student_instructor_summary(),public.instructor_add_note(uuid,text,boolean),public.instructor_create_goal(uuid,text,text,date),public.instructor_update_goal_status(uuid,text),public.instructor_schedule_session(uuid,timestamptz,integer,text,text),public.instructor_update_session(uuid,text,text) to authenticated;
