-- V3.3.1 coaching conversation + engagement/readiness metrics.
create table if not exists public.student_coaching_questions(id uuid primary key default gen_random_uuid(),assignment_id uuid not null references public.instructor_assignments(id) on delete cascade,student_id uuid not null references auth.users(id) on delete cascade,question text not null check(char_length(btrim(question)) between 1 and 1500),status text not null default 'open' check(status in ('open','answered','closed')),instructor_reply text,created_at timestamptz not null default now(),answered_at timestamptz);
create index if not exists idx_student_coaching_questions_assignment on public.student_coaching_questions(assignment_id,status,created_at desc);
create index if not exists idx_student_coaching_questions_student on public.student_coaching_questions(student_id,created_at desc);
alter table public.student_coaching_questions enable row level security;
drop policy if exists student_coaching_questions_read on public.student_coaching_questions;
create policy student_coaching_questions_read on public.student_coaching_questions for select to authenticated using(public.is_admin() or student_id=(select auth.uid()) or exists(select 1 from public.instructor_assignments a where a.id=student_coaching_questions.assignment_id and a.instructor_id=(select auth.uid())));
revoke insert,update,delete on public.student_coaching_questions from anon,authenticated;
grant select on public.student_coaching_questions to authenticated;
create or replace function public.student_submit_coaching_question(p_question text) returns uuid language plpgsql security definer set search_path='' as $$ declare v_assignment uuid; v_id uuid; begin if auth.uid() is null then raise exception 'Authentication required' using errcode='42501'; end if; if nullif(btrim(p_question),'') is null or char_length(btrim(p_question))>1500 then raise exception 'Question invalid' using errcode='22023'; end if; select id into v_assignment from public.instructor_assignments where student_id=auth.uid() and status='active' limit 1; if not found then raise exception 'No active instructor assignment' using errcode='42501'; end if; insert into public.student_coaching_questions(assignment_id,student_id,question) values(v_assignment,auth.uid(),btrim(p_question)) returning id into v_id; return v_id; end; $$;
create or replace function public.instructor_reply_coaching_question(p_question_id uuid,p_reply text,p_close boolean default false) returns boolean language plpgsql security definer set search_path='' as $$ begin if not public.is_instructor() then raise exception 'Instructor required' using errcode='42501'; end if; if nullif(btrim(p_reply),'') is null or char_length(btrim(p_reply))>3000 then raise exception 'Reply invalid' using errcode='22023'; end if; update public.student_coaching_questions q set instructor_reply=btrim(p_reply),status=case when coalesce(p_close,false) then 'closed' else 'answered' end,answered_at=now() where q.id=p_question_id and exists(select 1 from public.instructor_assignments a where a.id=q.assignment_id and (public.is_admin() or a.instructor_id=auth.uid())); return found; end; $$;
create or replace function public.get_learning_dashboard() returns jsonb language sql security definer stable set search_path='' as $$ with my_attempts as(select * from public.learning_attempts where user_id=auth.uid()), topic_stats as(select topic,count(*)::int attempts,count(*) filter(where is_correct is true)::int correct,round(100.0*count(*) filter(where is_correct is true)/nullif(count(*) filter(where is_correct is not null),0))::int accuracy from my_attempts where topic is not null and is_correct is not null group by topic), point_stats as(select coalesce(sum(points),0)::int points,count(*) filter(where kind='lesson')::int lesson_awards,count(*) filter(where kind='exam')::int exam_awards from public.learning_points_ledger where user_id=auth.uid()), base as(select count(*)::int attempts,count(*) filter(where is_correct is not null)::int answered,count(*) filter(where is_correct is true)::int correct,count(*) filter(where created_at::date=(now() at time zone 'UTC')::date)::int activity_today from my_attempts), active_days as(select distinct created_at::date d from my_attempts), streak as(select count(*)::int streak_days from(select d,row_number() over(order by d desc) rn from active_days where d<=(now() at time zone 'UTC')::date)x where d>=(now() at time zone 'UTC')::date-(rn::int-1) and not exists(select 1 from generate_series(0,rn::int-1) g(i) where((now() at time zone 'UTC')::date-g.i) not in(select d from active_days))), calc as(select b.*,p.points,p.lesson_awards,p.exam_awards,case when b.answered>0 then round(100.0*b.correct/b.answered)::int else 0 end accuracy,least(100,round(least(1.0,p.lesson_awards/9.0)*35+(case when b.answered>0 then(b.correct::numeric/b.answered) else 0 end)*35+least(1.0,p.exam_awards/3.0)*20+least(1.0,b.answered/100.0)*10)::int) readiness from base b cross join point_stats p) select jsonb_build_object('points',c.points,'attempts',c.attempts,'answered',c.answered,'correct',c.correct,'accuracy',c.accuracy,'activityToday',c.activity_today,'streakDays',coalesce((select streak_days from streak),0),'readiness',c.readiness,'level',case when c.points>=1200 then 'Expert' when c.points>=600 then 'Confirmé' when c.points>=250 then 'En progression' when c.points>=80 then 'Apprenti' else 'Débutant' end,'lessonAwards',c.lesson_awards,'examAwards',c.exam_awards,'weakTopics',coalesce((select jsonb_agg(jsonb_build_object('topic',topic,'attempts',attempts,'correct',correct,'accuracy',coalesce(accuracy,0)) order by coalesce(accuracy,0),attempts desc) from(select * from topic_stats where attempts>=2 order by coalesce(accuracy,0),attempts desc limit 6)s),'[]'::jsonb)) from calc c; $$;
revoke execute on function public.student_submit_coaching_question(text),public.instructor_reply_coaching_question(uuid,text,boolean) from public,anon;
grant execute on function public.student_submit_coaching_question(text),public.instructor_reply_coaching_question(uuid,text,boolean) to authenticated;
